name: Test

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest # define o ambiente que o teste acontece

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - run: mvn clean test